In [1]:
import numpy as np

class StandardScaler:
    def __init__(self):
        self.params = {}

    def fit(self, data):
        """
        Calculate and store the mean and standard deviation for each feature.
        
        Parameters:
        data (ndarray): 2D array where each column is a feature.
        """
        self.params['mean'] = np.mean(data, axis=0)
        self.params['std_dev'] = np.std(data, axis=0)

    def transform(self, data):
        """
        Standardize the data using the mean and standard deviation.
        
        Parameters:
        data (ndarray): 2D array where each column is a feature.
        
        Returns:
        ndarray: The standardized data.
        """
        return (data - self.params['mean']) / self.params['std_dev']

    def fit_transform(self, data):
        """
        Fit to the data and transform it.
        
        Parameters:
        data (ndarray): 2D array where each column is a feature.
        
        Returns:
        ndarray: The standardized data.
        """
        self.fit(data)
        return self.transform(data)

    def inverse_transform(self, data):
        """
        Revert the standardized data back to the original scale.
        
        Parameters:
        data (ndarray): 2D array where each column is a feature.
        
        Returns:
        ndarray: The data in the original scale.
        """
        return (data * self.params['std_dev']) + self.params['mean']

# Example usage:

# Sample data (3 features and 5 samples)
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0],
                 [10.0, 11.0, 12.0],
                 [13.0, 14.0, 15.0]])

# Initialize the scaler
scaler = StandardScaler()

# Standardize the data
standardized_data = scaler.fit_transform(data)

print("Standardized Data:")
print(standardized_data)

# Save the mean and standard deviation
print("Means:", scaler.params['mean'])
print("Standard Deviations:", scaler.params['std_dev'])

# Inverse transform to get back the original data
original_data = scaler.inverse_transform(standardized_data)
print("Original Data (reversed):")
print(original_data)


Standardized Data:
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
Means: [7. 8. 9.]
Standard Deviations: [4.24264069 4.24264069 4.24264069]
Original Data (reversed):
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
